apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-filestore
  namespace: poc-filestore
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: ""
  volumeName: pv-filestore   # Binding estático al PV de arriba