apiVersion: v1
kind: Service
metadata:
  name: sftp-server-svc
  namespace: poc-filestore
spec:
  type: ClusterIP      # Solo accesible dentro del cluster
  selector:
    app: sftp-server
  ports:
    - protocol: TCP
      port: 22
      targetPort: 22