server:
  port: 8080

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB

filestore:
  path: ${STORAGE_PATH:/mnt/filestore}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always