apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-filestore
  namespace: poc-filestore
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany          # NFS permite múltiples pods
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""       # Sin storage class dinámica
  mountOptions:
    - hard
    - nfsvers=3
  nfs:
    server: <MT_IP>        # Ej: 10.0.1.45
    path: /filestore
