apiVersion: v1
kind: Service
metadata:
  name: filestore-api-svc
  namespace: poc-filestore
  annotations:
    # OCI crea un Load Balancer público automáticamente
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
    service.beta.kubernetes.io/oci-load-balancer-subnet1: "<SUBNET_LB_OCID>"
spec:
  type: LoadBalancer
  selector:
    app: filestore-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
